@php
    // Guard and normalize incoming variables so this partial is safe to include anywhere
    $form    = $form    ?? null;
    $schema  = $schema  ?? [];
    $oldData = $oldData ?? [];
    $slug    = $slug    ?? 'step';
    $session = $session ?? null;

    // Ensure schema is an array even if JSON string was passed
    if (is_string($schema)) {
        $decoded = json_decode($schema, true);
        $schema = is_array($decoded) ? $decoded : [];
    }
@endphp

@if(!$form || !$session)
    <div class="text-sm text-gray-400">No form found for this step.</div>
@else
    @php
        // Prefill from ApprovedOrder meta if available
        /** @var \App\Models\ApprovedOrder|null $approved */
        $approved = ($session && $session->order instanceof \App\Models\ApprovedOrder)
            ? $session->order
            : (($session && $session->order_id) ? (\App\Models\ApprovedOrder::query()->find($session->order_id)) : null);

        $metaRaw = $approved?->meta ?? [];
        $metaArr = is_array($metaRaw) ? $metaRaw : (json_decode($metaRaw ?: '[]', true) ?: []);

        $selected = data_get($metaArr, 'selectedProduct')
                 ?? data_get($metaArr, 'items.0')
                 ?? data_get($metaArr, 'line_items.0')
                 ?? data_get($metaArr, 'cart.items.0')
                 ?? [];

        $prefill = [
            'date'     => now()->format('Y-m-d'),
            'product'  => data_get($selected, 'name') ?? data_get($metaArr, 'treatment') ?? null,
            'strength' => data_get($selected, 'variation') ?? data_get($selected, 'variations') ?? data_get($metaArr, 'strength') ?? null,
            'quantity' => data_get($selected, 'quantity') ?? data_get($metaArr, 'quantity') ?? null,
            'notes'    => data_get($metaArr, 'notes') ?? data_get($metaArr, 'clinical_notes') ?? null,
        ];
    @endphp

    <form id="cf_{{ $slug }}" method="POST" action="{{ route('consultations.forms.save', ['session' => $session->id, 'form' => $form->id]) }}?tab={{ $slug }}" class="space-y-4">
        @csrf
        <input type="hidden" name="__step_slug" value="{{ $slug }}">

        @forelse($schema as $i => $field)
            @php
                $type = $field['type'] ?? 'text_input';
                $cfg  = (array)($field['data'] ?? []);
                $name = $field['name'] ?? ($type === 'text_block' ? 'block_'.$i : 'field_'.$i);
                $label= $cfg['label'] ?? ($field['label'] ?? ucfirst(str_replace('_',' ',$name)));
                $req  = (bool)($cfg['required'] ?? false);

                // smart default based on label keywords (works even if names are autogenerated)
                $labelLower = strtolower((string)$label);
                $defaultFromMeta = null;
                if ($type === 'date') {
                    $defaultFromMeta = $prefill['date'];
                } elseif ($type === 'select') {
                    $defaultFromMeta = $prefill['product'];
                } elseif (str_contains($labelLower, 'strength') || str_contains($labelLower, 'dose')) {
                    $defaultFromMeta = $prefill['strength'];
                } elseif (str_contains($labelLower, 'quantity')) {
                    $defaultFromMeta = $prefill['quantity'];
                } elseif (str_contains($labelLower, 'note')) {
                    $defaultFromMeta = $prefill['notes'];
                }

                $val  = old($name, $oldData[$name] ?? $defaultFromMeta);
            @endphp

            @if($type === 'text_block')
                <div class="rounded-md border border-gray-700/60 bg-gray-900/50 p-6">
                    {!! $cfg['content'] ?? '' !!}
                </div>

            @elseif($type === 'checkbox')
                <label class="inline-flex items-center gap-2 text-sm text-gray-200">
                    <input type="checkbox" name="{{ $name }}" class="rounded bg-gray-800 border-gray-600" @checked((bool)$val) @if($req) required @endif>
                    <span>{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</span>
                </label>
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror

            @elseif($type === 'date')
                <label class="block text-sm text-gray-300 mb-1">{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</label>
                <input type="date" name="{{ $name }}" value="{{ \Illuminate\Support\Str::of((string)($val ?? ($cfg['date'] ?? '')))->limit(10,'') }}" @if($req) required @endif class="w-full rounded-md bg-gray-800 border border-gray-600 p-2 text-gray-100">
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror

            @elseif($type === 'number')
                <label class="block text-sm text-gray-300 mb-1">{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</label>
                @php $stepAttr = $cfg['step'] ?? ((str_contains($labelLower,'strength') || str_contains($labelLower,'dose')) ? '0.1' : 'any'); @endphp
                <input type="number" name="{{ $name }}" value="{{ $val }}" @if($req) required @endif step="{{ $stepAttr }}" inputmode="decimal" class="w-full rounded-md bg-gray-800 border border-gray-600 p-2 text-gray-100">
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror

            @elseif($type === 'select')
                <label class="block text-sm text-gray-300 mb-1">{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</label>
                <select name="{{ $name }}" @if($req) required @endif class="w-full rounded-md bg-gray-800 border border-gray-600 p-2 text-gray-100">
                    @foreach((array)($cfg['options'] ?? []) as $ov => $ol)
                        @php
                            $optValue = is_array($ol) ? ($ol['value'] ?? $ov) : $ov;
                            $optLabel = is_array($ol) ? ($ol['label'] ?? ($ol['value'] ?? $ov)) : $ol;
                        @endphp
                        <option value="{{ $optValue }}" @selected((string)$val === (string)$optValue)>{{ $optLabel }}</option>
                    @endforeach
                </select>
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror

            @elseif($type === 'signature')
                <label class="block text-sm text-gray-300 mb-1">{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</label>
                <input type="text" name="{{ $name }}" value="{{ $val }}" @if($req) required @endif class="w-full rounded-md bg-gray-800 border border-gray-600 p-2 text-gray-100" placeholder="signature data url">
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror

            @else
                <label class="block text-sm text-gray-300 mb-1">{{ $label }} @if($req)<span class="text-red-500">*</span>@endif</label>
                <input type="text" name="{{ $name }}" value="{{ $val }}" @if($req) required @endif class="w-full rounded-md bg-gray-800 border border-gray-600 p-2 text-gray-100">
                @error($name) <p class="text-xs text-red-400 mt-1">{{ $message }}</p> @enderror
            @endif
        @empty
            <div class="text-sm text-gray-400">This form has no fields yet.</div>
        @endforelse

        {{-- Intentionally no internal Save buttons; the page-level buttons handle submission/navigation --}}
    </form>
@endif

{{-- Global Consultation Forms Modal (mounted once) --}}
<div
  x-data="{
    open:false, title:'', url:'', loading:false,
    openModal(t,u){ this.title=t; this.url=u; this.open=true; this.loading=true; },
    close(){ this.open=false; this.loading=false; this.title=''; this.url=''; }
  }"
  x-ref="formsModal"
  x-on:keydown.escape.window="close()"
  x-cloak
>
  <template x-if="open">
    <div class="fixed inset-0 z-[100] flex items-center justify-center">
      <div class="absolute inset-0 bg-black/60" @click="close()"></div>
      <div class="relative rounded-2xl w-[min(1100px,95vw)] max-h-[85vh] overflow-hidden" style="background:#0b0b0b;box-shadow:none;border:0;">
        <div class="flex items-center justify-between px-5 py-3">
          <h3 class="text-sm font-semibold text-gray-200" x-text="title || 'Form'"></h3>
          <button type="button" class="text-gray-300 hover:text-white" @click="close()" aria-label="Close">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>
          </button>
        </div>
        <div class="relative" style="height: 75vh; background:#0b0b0b;">
          <template x-if="loading">
            <div class="absolute inset-0 flex items-center justify-center">
              <div class="text-sm text-gray-400">Loading…</div>
            </div>
          </template>
          <iframe :src="url" class="w-full h-full" style="display:block;width:100%;height:100%;border:0;background:#0b0b0b;color:#fff;" frameborder="0" @load="loading=false" referrerpolicy="no-referrer"></iframe>
        </div>
      </div>
    </div>
  </template>

  <script>
    // Register a global opener once. If multiple _form.blade.php are included, first wins.
    (function(){
      if (window.__openConsultationModal) return;
      document.addEventListener('alpine:init', () => {
        window.__openConsultationModal = (title, url) => {
          const el = document.querySelector('[x-ref=\'formsModal\']');
          if (el && el.__x && el.__x.$data) {
            el.__x.$data.openModal(title, url);
          } else {
            // Fallback: navigate if modal not mounted
            window.location.href = url;
          }
        };
      });
    })();
  </script>
</div>